In [40]:
# Dependencies

import pandas as pd


# load the data from csv to pandas dataframe
Healthcare_Provider_raw = pd.read_csv("data/Train-1542865627584.csv")
Healthcare_Beneficiary_raw = pd.read_csv("data/Train_Beneficiarydata-1542865627584.csv")
Healthcare_Inpatient_raw = pd.read_csv("data/Train_Inpatientdata-1542865627584.csv")
Healthcare_Outpatient_raw = pd.read_csv("data/Train_Outpatientdata-1542865627584.csv")

In [44]:
# Assign inpatient data as 1, outpatient data as 0

Healthcare_Inpatient_raw['In_Out']=1
Healthcare_Outpatient_raw['In_Out']=0

In [45]:
Healthcare_Inpatient_raw.columns,Healthcare_Outpatient_raw.columns

(Index(['BeneID', 'ClaimID', 'ClaimStartDt', 'ClaimEndDt', 'Provider',
        'InscClaimAmtReimbursed', 'AttendingPhysician', 'OperatingPhysician',
        'OtherPhysician', 'AdmissionDt', 'ClmAdmitDiagnosisCode',
        'DeductibleAmtPaid', 'DischargeDt', 'DiagnosisGroupCode',
        'ClmDiagnosisCode_1', 'ClmDiagnosisCode_2', 'ClmDiagnosisCode_3',
        'ClmDiagnosisCode_4', 'ClmDiagnosisCode_5', 'ClmDiagnosisCode_6',
        'ClmDiagnosisCode_7', 'ClmDiagnosisCode_8', 'ClmDiagnosisCode_9',
        'ClmDiagnosisCode_10', 'ClmProcedureCode_1', 'ClmProcedureCode_2',
        'ClmProcedureCode_3', 'ClmProcedureCode_4', 'ClmProcedureCode_5',
        'ClmProcedureCode_6', 'In_Out'],
       dtype='object'),
 Index(['BeneID', 'ClaimID', 'ClaimStartDt', 'ClaimEndDt', 'Provider',
        'InscClaimAmtReimbursed', 'AttendingPhysician', 'OperatingPhysician',
        'OtherPhysician', 'ClmDiagnosisCode_1', 'ClmDiagnosisCode_2',
        'ClmDiagnosisCode_3', 'ClmDiagnosisCode_4', 'ClmDiagnosisCode_5',
        'ClmDiagnosisCode_6', 'ClmDiagnosisCode_7', 'ClmDiagnosisCode_8',
        'ClmDiagnosisCode_9', 'ClmDiagnosisCode_10', 'ClmProcedureCode_1',
        'ClmProcedureCode_2', 'ClmProcedureCode_3', 'ClmProcedureCode_4',
        'ClmProcedureCode_5', 'ClmProcedureCode_6', 'DeductibleAmtPaid',
        'ClmAdmitDiagnosisCode', 'In_Out'],
       dtype='object'))

In [46]:
# union/concat the inpatient and outpatient data
concat_df=pd.concat([Healthcare_Inpatient_raw,Healthcare_Outpatient_raw],axis=0)
concat_df.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,...,ClmDiagnosisCode_8,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6,In_Out
0,BENE11001,CLM46614,2009-04-12,2009-04-18,PRV55912,26000,PHY390922,NaN,NaN,2009-04-12,...,19889,5849,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,BENE11001,CLM66048,2009-08-31,2009-09-02,PRV55907,5000,PHY318495,PHY318495,NaN,2009-08-31,...,NaN,NaN,NaN,7092.0,NaN,NaN,NaN,NaN,NaN,1
2,BENE11001,CLM68358,2009-09-17,2009-09-20,PRV56046,5000,PHY372395,NaN,PHY324689,2009-09-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
3,BENE11011,CLM38412,2009-02-14,2009-02-22,PRV52405,5000,PHY369659,PHY392961,PHY349768,2009-02-14,...,40390,4019,NaN,331.0,NaN,NaN,NaN,NaN,NaN,1
4,BENE11014,CLM63689,2009-08-13,2009-08-30,PRV56614,10000,PHY379376,PHY398258,NaN,2009-08-13,...,29620,20300,NaN,3893.0,NaN,NaN,NaN,NaN,NaN,1

In [47]:
merge_bene_df=concat_df.merge(Healthcare_Beneficiary_raw, on='BeneID', how='left')
merge_bene_df.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,...,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
0,BENE11001,CLM46614,2009-04-12,2009-04-18,PRV55912,26000,PHY390922,NaN,NaN,2009-04-12,...,1,1,1,2,1,1,36000,3204,60,70
1,BENE11001,CLM66048,2009-08-31,2009-09-02,PRV55907,5000,PHY318495,PHY318495,NaN,2009-08-31,...,1,1,1,2,1,1,36000,3204,60,70
2,BENE11001,CLM68358,2009-09-17,2009-09-20,PRV56046,5000,PHY372395,NaN,PHY324689,2009-09-17,...,1,1,1,2,1,1,36000,3204,60,70
3,BENE11011,CLM38412,2009-02-14,2009-02-22,PRV52405,5000,PHY369659,PHY392961,PHY349768,2009-02-14,...,1,1,2,2,1,1,5000,1068,250,320
4,BENE11014,CLM63689,2009-08-13,2009-08-30,PRV56614,10000,PHY379376,PHY398258,NaN,2009-08-13,...,1,2,1,2,2,2,21260,2136,120,100

In [48]:
merge_provider_df=merge_bene_df.merge(Healthcare_Provider_raw, on = 'Provider', how ='left')
merge_provider_df.drop_duplicates(inplace=True)
merge_provider_df

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,...,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt,PotentialFraud
0,BENE11001,CLM46614,2009-04-12,2009-04-18,PRV55912,26000,PHY390922,NaN,NaN,2009-04-12,...,1,1,2,1,1,36000,3204,60,70,Yes
1,BENE11001,CLM66048,2009-08-31,2009-09-02,PRV55907,5000,PHY318495,PHY318495,NaN,2009-08-31,...,1,1,2,1,1,36000,3204,60,70,No
2,BENE11001,CLM68358,2009-09-17,2009-09-20,PRV56046,5000,PHY372395,NaN,PHY324689,2009-09-17,...,1,1,2,1,1,36000,3204,60,70,No
3,BENE11011,CLM38412,2009-02-14,2009-02-22,PRV52405,5000,PHY369659,PHY392961,PHY349768,2009-02-14,...,1,2,2,1,1,5000,1068,250,320,No
4,BENE11014,CLM63689,2009-08-13,2009-08-30,PRV56614,10000,PHY379376,PHY398258,NaN,2009-08-13,...,2,1,2,2,2,21260,2136,120,100,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
558206,BENE159198,CLM510792,2009-08-06,2009-08-06,PRV53699,800,PHY364188,PHY364188,PHY385752,NaN,...,1,2,2,1,2,0,0,5470,1870,No
558207,BENE159198,CLM551294,2009-08-29,2009-08-29,PRV53702,400,PHY423019,PHY332284,NaN,NaN,...,1,2,2,1,2,0,0,5470,1870,No
558208,BENE159198,CLM596444,2009-09-24,2009-09-24,PRV53676,60,PHY361063,NaN,NaN,NaN,...,1,2,2,1,2,0,0,5470,1870,No
558209,BENE159198,CLM636992,2009-10-18,2009-10-18,PRV53689,70,PHY403198,NaN,PHY419379,NaN,...,1,2,2,1,2,0,0,5470,1870,No
558210,BENE159198,CLM686139,2009-11-17,2009-11-18,PRV53689,80,PHY419379,NaN,PHY419379,NaN,...,1,2,2,1,2,0,0,5470,1870,No

In [50]:
# calculte claimPeriod and HospitalizedDays
merge_df_transform = merge_provider_df.copy(deep=True)
merge_df_transform['ClaimPeriod'] = (pd.to_datetime(merge_df_transform.ClaimEndDt) - pd.to_datetime(merge_df_transform.ClaimStartDt)).dt.days + 1
merge_df_transform['HospitalizedDays'] = (pd.to_datetime(merge_df_transform.DischargeDt) - pd.to_datetime(merge_df_transform.AdmissionDt)).dt.days + 1
# make hospitallized day 0 for outpatient
merge_df_transform['HospitalizedDays'] = merge_df_transform['HospitalizedDays'].apply(lambda x : 0 if pd.isna(x) else x )

In [53]:
merge_df_transform['Deceased'] = merge_df_transform['DOD'].apply(lambda x : 0 if pd.isna(x) else 1)

In [54]:
#calculate age and determine if a person is deceased. If the person is still alive, 
#use '2009-12-01' as the time we calculate age

from datetime import date, datetime
def calulateAge(dob, dod, calulationDate):
    born = datetime.strptime(dob, "%Y-%m-%d").date()
    if not pd.isna(dod):
        calulationDate = datetime.strptime(dod, "%Y-%m-%d").date()
    else:
        calulationDate = datetime.strptime(calulationDate, "%Y-%m-%d").date()
    return calulationDate.year - born.year - ((calulationDate.month, calulationDate.day) < (born.month, born.day))    



merge_df_transform['Age'] = merge_df_transform.apply(lambda x: calulateAge(dob = x['DOB'], dod = x['DOD'], calulationDate = '2009-12-01'), axis = 1)

In [55]:
#Transform potential fraud to 1/0
merge_df_transform['PotentialFraud'] = merge_df_transform['PotentialFraud'].apply(lambda x : 1 if x == 'Yes' else 0)

In [56]:
'''columns: list of columns ['ClmDiagnosisCode_1', 'ClmDiagnosisCode_2']'''
def countCodeNumbers(df, columns):
    df_codes = merge_df_transform.loc[:, columns]
    codecount = df_codes.notnull().sum(axis=1)
    return codecount

diagnosis_code_columns = ['ClmDiagnosisCode_1', 'ClmDiagnosisCode_2', 'ClmDiagnosisCode_3', 'ClmDiagnosisCode_4', 'ClmDiagnosisCode_5', 
           'ClmDiagnosisCode_6', 'ClmDiagnosisCode_7', 'ClmDiagnosisCode_8', 'ClmDiagnosisCode_9', 'ClmDiagnosisCode_10' ]
procedure_code_columns = ['ClmProcedureCode_1', 'ClmProcedureCode_2', 'ClmProcedureCode_3',
       'ClmProcedureCode_4', 'ClmProcedureCode_5', 'ClmProcedureCode_6']

merge_df_transform['DiagnosisCodeCount'] = countCodeNumbers(merge_df_transform, diagnosis_code_columns)
merge_df_transform['ProcedureCodeCount'] = countCodeNumbers(merge_df_transform, procedure_code_columns)

In [57]:
merge_df_transform['DiagnosisGroupCode'] = merge_df_transform['DiagnosisGroupCode'].apply(lambda x: -999 if pd.isna(x) else x)

In [39]:
#Drop unecessary columns
dropColumnList = ['ClaimID', 'ClaimStartDt', 'ClaimEndDt', 'AdmissionDt', 'DischargeDt', 'DOB', 'DOD', ]
merge_df_transform.drop(axis = 1, columns=dropColumnList, inplace=True)

In [37]:
merge_df_transform

,BeneID,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,ClmAdmitDiagnosisCode,DeductibleAmtPaid,DiagnosisGroupCode,ClmDiagnosisCode_1,...,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt,PotentialFraud,ClaimPeriod,HospitalizedDays,Deceased,Age,DiagnosisCodeCount,ProcedureCodeCount
0,BENE11001,PRV55912,26000,PHY390922,NaN,NaN,7866,1068.0,201,1970,...,3204,60,70,1,7,7.0,0,66,9,0
1,BENE11001,PRV55907,5000,PHY318495,PHY318495,NaN,6186,1068.0,750,6186,...,3204,60,70,0,3,3.0,0,66,3,1
2,BENE11001,PRV56046,5000,PHY372395,NaN,PHY324689,29590,1068.0,883,29623,...,3204,60,70,0,4,4.0,0,66,6,0
3,BENE11011,PRV52405,5000,PHY369659,PHY392961,PHY349768,431,1068.0,067,43491,...,1068,250,320,0,9,9.0,0,95,9,1
4,BENE11014,PRV56614,10000,PHY379376,PHY398258,NaN,78321,1068.0,975,042,...,2136,120,100,0,18,18.0,0,71,9,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
558206,BENE159198,PRV53699,800,PHY364188,PHY364188,PHY385752,NaN,0.0,-999,2163,...,0,5470,1870,0,1,0.0,0,57,3,0
558207,BENE159198,PRV53702,400,PHY423019,PHY332284,NaN,NaN,0.0,-999,07041,...,0,5470,1870,0,1,0.0,0,57,3,0
558208,BENE159198,PRV53676,60,PHY361063,NaN,NaN,NaN,0.0,-999,V570,...,0,5470,1870,0,1,0.0,0,57,2,0
558209,BENE159198,PRV53689,70,PHY403198,NaN,PHY419379,NaN,0.0,-999,NaN,...,0,5470,1870,0,1,0.0,0,57,0,0
558210,BENE159198,PRV53689,80,PHY419379,NaN,PHY419379,NaN,0.0,-999,78900,...,0,5470,1870,0,2,0.0,0,57,8,0

In [58]:
provider_agg_df = pd.DataFrame()
provider_agg_df['Provider'] = Healthcare_Provider_raw.Provider

In [61]:
HospitalDays = merge_df_transform.groupby('Provider').agg(MaxHospitalDays = ('HospitalizedDays', 'max'), 
                                                       MedianHospitalDays = ('HospitalizedDays', 'median'),
                                                       MeanHospitalDays = ('HospitalizedDays', 'mean'))

In [62]:
HospitalDays

          MaxHospitalDays  MedianHospitalDays  MeanHospitalDays
Provider
PRV51001             15.0                 0.0          1.200000
PRV51003             28.0                 0.0          2.893939
PRV51004              0.0                 0.0          0.000000
PRV51005              0.0                 0.0          0.000000
PRV51007              8.0                 0.0          0.263889
...                   ...                 ...               ...
PRV57759              0.0                 0.0          0.000000
PRV57760              0.0                 0.0          0.000000
PRV57761              0.0                 0.0          0.000000
PRV57762              0.0                 0.0          0.000000
PRV57763              0.0                 0.0          0.000000

[5410 rows x 3 columns]

In [63]:
provider_agg_df=provider_agg_df.merge(HospitalDays, on = 'Provider', how ='left')
provider_agg_df

      Provider  MaxHospitalDays  MedianHospitalDays  MeanHospitalDays
0     PRV51001             15.0                 0.0          1.200000
1     PRV51003             28.0                 0.0          2.893939
2     PRV51004              0.0                 0.0          0.000000
3     PRV51005              0.0                 0.0          0.000000
4     PRV51007              8.0                 0.0          0.263889
...        ...              ...                 ...               ...
5405  PRV57759              0.0                 0.0          0.000000
5406  PRV57760              0.0                 0.0          0.000000
5407  PRV57761              0.0                 0.0          0.000000
5408  PRV57762              0.0                 0.0          0.000000
5409  PRV57763              0.0                 0.0          0.000000

[5410 rows x 4 columns]

In [64]:
merge_df_transform.columns

Index(['BeneID', 'ClaimID', 'ClaimStartDt', 'ClaimEndDt', 'Provider',
       'InscClaimAmtReimbursed', 'AttendingPhysician', 'OperatingPhysician',
       'OtherPhysician', 'AdmissionDt', 'ClmAdmitDiagnosisCode',
       'DeductibleAmtPaid', 'DischargeDt', 'DiagnosisGroupCode',
       'ClmDiagnosisCode_1', 'ClmDiagnosisCode_2', 'ClmDiagnosisCode_3',
       'ClmDiagnosisCode_4', 'ClmDiagnosisCode_5', 'ClmDiagnosisCode_6',
       'ClmDiagnosisCode_7', 'ClmDiagnosisCode_8', 'ClmDiagnosisCode_9',
       'ClmDiagnosisCode_10', 'ClmProcedureCode_1', 'ClmProcedureCode_2',
       'ClmProcedureCode_3', 'ClmProcedureCode_4', 'ClmProcedureCode_5',
       'ClmProcedureCode_6', 'In_Out', 'DOB', 'DOD', 'Gender', 'Race',
       'RenalDiseaseIndicator', 'State', 'County', 'NoOfMonths_PartACov',
       'NoOfMonths_PartBCov', 'ChronicCond_Alzheimer',
       'ChronicCond_Heartfailure', 'ChronicCond_KidneyDisease',
       'ChronicCond_Cancer', 'ChronicCond_ObstrPulmonary',
       'ChronicCond_Depression', 'ChronicCond_Diabetes',
       'ChronicCond_IschemicHeart', 'ChronicCond_Osteoporasis',
       'ChronicCond_rheumatoidarthritis', 'ChronicCond_stroke',
       'IPAnnualReimbursementAmt', 'IPAnnualDeductibleAmt',
       'OPAnnualReimbursementAmt', 'OPAnnualDeductibleAmt', 'PotentialFraud',
       'ClaimPeriod', 'HospitalizedDays', 'Deceased', 'Age',
       'DiagnosisCodeCount', 'ProcedureCodeCount'],
      dtype='object')

In [65]:
provider_agg_df['Chronic_Alzheimer_Frac'] = merge_df_transform.groupby('Provider').apply(lambda x: (x['ChronicCond_Alzheimer'] == 1).sum()/x['ChronicCond_Alzheimer'].count())

In [81]:
Chronic_Alzheimer_Frac = merge_df_transform.groupby('Provider').apply(lambda x: (x['ChronicCond_Alzheimer'] == 1).sum()/x['ChronicCond_Alzheimer'].count())
Chronic_Alzheimer_Frac.values

array([0.6       , 0.42424242, 0.4295302 , ..., 0.43902439, 0.        ,
       0.38135593])

In [82]:
provider_agg_df['Chronic_Alzheimer_Frac'] = (merge_df_transform.groupby('Provider').apply(lambda x: (x['ChronicCond_Alzheimer'] == 1).sum()/x['ChronicCond_Alzheimer'].count())).values

In [84]:
provider_agg_df['Chronic_Heartfailure_Frac'] = (merge_df_transform.groupby('Provider').apply(lambda x: (x['ChronicCond_Heartfailure'] == 1).sum()/x['ChronicCond_Heartfailure'].count())).values

In [86]:
provider_agg_df['Chronic_KidneyDisease_Frac'] = (merge_df_transform.groupby('Provider').apply(lambda x: (x['ChronicCond_KidneyDisease'] == 1).sum()/x['ChronicCond_KidneyDisease'].count())).values

In [88]:
provider_agg_df['Chronic_Cancer_Frac'] = (merge_df_transform.groupby('Provider').apply(lambda x: (x['ChronicCond_Cancer'] == 1).sum()/x['ChronicCond_Cancer'].count())).values

In [89]:
provider_agg_df['Chronic_ObstrPulmonary_Frac'] = (merge_df_transform.groupby('Provider').apply(lambda x: (x['ChronicCond_ObstrPulmonary'] == 1).sum()/x['ChronicCond_ObstrPulmonary'].count())).values

In [90]:
provider_agg_df['Chronic_Depression_Frac'] = (merge_df_transform.groupby('Provider').apply(lambda x: (x['ChronicCond_Depression'] == 1).sum()/x['ChronicCond_Depression'].count())).values

In [92]:
provider_agg_df['Chronic_Diabetes_Frac'] = (merge_df_transform.groupby('Provider').apply(lambda x: (x['ChronicCond_Diabetes'] == 1).sum()/x['ChronicCond_Diabetes'].count())).values

In [93]:
provider_agg_df['Chronic_IschemicHeart_Frac'] = (merge_df_transform.groupby('Provider').apply(lambda x: (x['ChronicCond_IschemicHeart'] == 1).sum()/x['ChronicCond_IschemicHeart'].count())).values

In [94]:
provider_agg_df['Chronic_Osteoporasis_Frac'] = (merge_df_transform.groupby('Provider').apply(lambda x: (x['ChronicCond_Osteoporasis'] == 1).sum()/x['ChronicCond_Osteoporasis'].count())).values

In [95]:
provider_agg_df['Chronic_rheumatoidarthritis_Frac'] = (merge_df_transform.groupby('Provider').apply(lambda x: (x['ChronicCond_rheumatoidarthritis'] == 1).sum()/x['ChronicCond_rheumatoidarthritis'].count())).values

In [96]:
provider_agg_df['Chronic_stroke_Frac'] = (merge_df_transform.groupby('Provider').apply(lambda x: (x['ChronicCond_stroke'] == 1).sum()/x['ChronicCond_stroke'].count())).values

In [97]:
provider_agg_df

,Provider,MaxHospitalDays,MedianHospitalDays,MeanHospitalDays,Chronic_Alzheimer_Frac,Chronic_Heartfailure_Frac,Chronic_KidneyDisease_Frac,Chronic_Cancer_Frac,Chronic_ObstrPulmonary_Frac,Chronic_Depression_Frac,Chronic_Diabetes_Frac,Chronic_IschemicHeart_Frac,Chronic_Osteoporasis_Frac,Chronic_rheumatoidarthritis_Frac,Chronic_stroke_Frac
0,PRV51001,15.0,0.0,1.200000,0.600000,0.760000,0.680000,0.200000,0.400000,0.360000,0.840000,0.920000,0.240000,0.320000,0.240000
1,PRV51003,28.0,0.0,2.893939,0.424242,0.606061,0.484848,0.075758,0.310606,0.409091,0.757576,0.848485,0.250000,0.287879,0.090909
2,PRV51004,0.0,0.0,0.000000,0.429530,0.590604,0.335570,0.107383,0.275168,0.422819,0.704698,0.724832,0.328859,0.308725,0.114094
3,PRV51005,0.0,0.0,0.000000,0.365665,0.583691,0.435193,0.141631,0.253219,0.416309,0.685837,0.768240,0.295279,0.284120,0.106438
4,PRV51007,8.0,0.0,0.263889,0.361111,0.555556,0.305556,0.166667,0.222222,0.402778,0.680556,0.708333,0.291667,0.305556,0.166667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5405,PRV57759,0.0,0.0,0.000000,0.500000,0.714286,0.535714,0.142857,0.392857,0.321429,0.714286,1.000000,0.464286,0.321429,0.142857
5406,PRV57760,0.0,0.0,0.000000,0.136364,0.500000,0.090909,0.000000,0.090909,0.318182,0.818182,1.000000,0.500000,0.045455,0.000000
5407,PRV57761,0.0,0.0,0.000000,0.439024,0.682927,0.487805,0.170732,0.365854,0.463415,0.670732,0.756098,0.390244,0.292683,0.121951
5408,PRV57762,0.0,0.0,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000
5409,PRV57763,0.0,0.0,0.000000,0.381356,0.533898,0.389831,0.203390,0.381356,0.525424,0.711864,0.754237,0.288136,0.372881,0.050847